### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by ChaoticWeevil** [weirdybeardyman/settlrs#1]
Hi this does seem to be quite a good example of a turn based strategy game however it does seem to be missing a lot of files. Not sure if you just put this up here to store some assets but it is missing a project.godot + lots of scene and the scenes that are there are missing some dependencies.

**Comment by weirdybeardyman** [comment]
Hey there, you're right, I haven't uploaded any of the project files, scenes or assets yet, just the code as I haven't quite settled on the final implementation of some things and the project is a bit of a mess. I will tidy it up and upload everything so it is usable ASAP. I should reach ~0.7 with fog of war implemented today so I will try and publish a useable project by 06/08/2020

**Comment by weirdybeardyman** [comment]
Ok 0.7 implemented, this project should now be useable.
